modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
modId="changed_addon"
version="2.7.2"
displayName="Changed Addon Plus"
credits="0senia0 (Helper Dev)\nLTXProgrammer (Main Mod Dev)\n Donators : Nazaeura, Axivorn, BlockyBreaker9001, BRUH, Deathswordd, LostyBoy, Dawn The Shark, MÃ¡rk Fazekas, fengqi, The_Snowwy_Snom Nom, Memenius, breadikals, Rosa Garcia Lobos, justin colburn"
displayURL="https://www.curseforge.com/minecraft/mc-mods/changed-addon-plus/"
updateJSONURL="https://raw.githubusercontent.com/Foxyas/check-mods-update/main/Changed-Addon-Update-Check"
logoFile="logo.png"
authors="Foxyas (Main Dev) \n 0senia0 (Helper Dev)"
description="this is a remastered version of my mod addon hope you like it! \n If you want to help me by donating some money this is my patreon https://www.patreon.com/Changedaddonplus"

[[dependencies.changed_addon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.changed_addon]]
    modId="forge"
    mandatory=true
    versionRange="[47.4.0,)"
    ordering="NONE"
    side="BOTH"


[[dependencies.changed_addon]]
    modId="changed"
    mandatory=true
    versionRange="[0.15.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.changed_addon]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

